// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHzmW_sjPfIb0M69C2QpeD1-I4JlTwF_0',
    appId: '1:1064678498773:web:f0fef5ddd3cbf9e66a5d5c',
    messagingSenderId: '1064678498773',
    projectId: 'thoughts-tracker-e36c2',
    authDomain: 'thoughts-tracker-e36c2.firebaseapp.com',
    storageBucket: 'thoughts-tracker-e36c2.firebasestorage.app',
    measurementId: 'G-S4RCRYWETW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdaK76XBn1QhPO6zCzmibVJ9Jme9Szvao',
    appId: '1:1064678498773:android:f227333478f078846a5d5c',
    messagingSenderId: '1064678498773',
    projectId: 'thoughts-tracker-e36c2',
    storageBucket: 'thoughts-tracker-e36c2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHzmW_sjPfIb0M69C2QpeD1-I4JlTwF_0',
    appId: '1:1064678498773:web:4ca85227719069586a5d5c',
    messagingSenderId: '1064678498773',
    projectId: 'thoughts-tracker-e36c2',
    authDomain: 'thoughts-tracker-e36c2.firebaseapp.com',
    storageBucket: 'thoughts-tracker-e36c2.firebasestorage.app',
    measurementId: 'G-Q3G2SG318R',
  );
}
